import { GoogleGenerativeAI } from '@google/generative-ai'
import { logTokenUsage } from '@/lib/usage'

const GEMINI_MODEL = process.env.GEMINI_MODEL ?? 'gemini-2.0-flash-001'

// ── Gemini ─────────────────────────────────────────────────────────────────

async function geminiGenerate(prompt: string): Promise<string> {
  const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!)
  const model = genAI.getGenerativeModel({ model: GEMINI_MODEL })
  const result = await model.generateContent(prompt)
  const response = result.response
  const usage = response.usageMetadata
  logTokenUsage({
    agent: 'Logos',
    model: GEMINI_MODEL,
    provider: 'gemini',
    promptTokens: usage?.promptTokenCount ?? 0,
    completionTokens: usage?.candidatesTokenCount ?? 0,
  })
  return response.text()
}

// ── Guide Generation ───────────────────────────────────────────────────────

export interface LogosGuide {
  title: string
  scripture: string
  reflection: string
  prayer: string
  application: string
}

export async function generateGuide(topic: string, scripture?: string): Promise<LogosGuide> {
  const scriptureHint = scripture ? `Anchor scripture: ${scripture}` : ''

  const prompt = `You are Logos, a devotional writer for TheoSYN AI. You create warm, scripture-rooted digital guides for Christians — written for everyday believers, not seminary students.

Generate a complete devotional guide on the topic: "${topic}"
${scriptureHint}

The guide must follow this exact structure:
1. TITLE: A compelling, warm title (not just the topic name)
2. SCRIPTURE: A specific Bible verse or short passage (with reference) that anchors the devotional
3. REFLECTION: 3-4 paragraphs of thoughtful, personal reflection on the scripture and topic. Faith-informed, honest, and practical. Not preachy. Speak to real life.
4. PRAYER: A 2-3 sentence heartfelt prayer in first person that flows naturally from the reflection
5. APPLICATION: 2-3 concrete, practical steps the reader can take this week to live out this truth

Tone: warm, honest, grounded in scripture, accessible to any Christian regardless of denomination.

Return JSON with exactly these fields:
{
  "title": "...",
  "scripture": "verse text — Reference",
  "reflection": "...",
  "prayer": "...",
  "application": "..."
}

Write only the JSON. No other text.`

  const raw = await geminiGenerate(prompt)

  try {
    const clean = raw.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim()
    return JSON.parse(clean)
  } catch {
    // Fallback structure if JSON parse fails
    return {
      title: topic,
      scripture: scripture ?? '',
      reflection: raw,
      prayer: '',
      application: '',
    }
  }
}

// ── Google Drive ───────────────────────────────────────────────────────────

export async function uploadGuideToDrive(
  guide: LogosGuide,
  accessToken: string
): Promise<{ fileId: string; url: string } | null> {
  const folderId = process.env.LOGOS_DRIVE_FOLDER_ID

  const docContent = `${guide.title}

📖 SCRIPTURE
${guide.scripture}

✦ REFLECTION
${guide.reflection}

🙏 PRAYER
${guide.prayer}

✅ APPLICATION
${guide.application}

---
Generated by Logos — TheoSYN AI
`

  const metadata = {
    name: guide.title,
    mimeType: 'application/vnd.google-apps.document',
    ...(folderId ? { parents: [folderId] } : {}),
  }

  // Create the Google Doc
  const form = new FormData()
  form.append('metadata', new Blob([JSON.stringify(metadata)], { type: 'application/json' }))
  form.append('file', new Blob([docContent], { type: 'text/plain' }))

  const res = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart',
    {
      method: 'POST',
      headers: { Authorization: `Bearer ${accessToken}` },
      body: form,
    }
  )

  if (!res.ok) {
    console.error('[Logos] Drive upload failed:', await res.text())
    return null
  }

  const file = await res.json()
  const fileId = file.id

  // Make it viewable by anyone with the link
  await fetch(`https://www.googleapis.com/drive/v3/files/${fileId}/permissions`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ role: 'reader', type: 'anyone' }),
  })

  return {
    fileId,
    url: `https://docs.google.com/document/d/${fileId}/edit`,
  }
}
